
insert into EMPLOYEE (id, first_name, last_name, company) values (1, 'Keri', 'Lee', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (2, 'Dollie R.', 'Schnidt', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (3, 'Cornelia J.', 'LeClerc', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (4, 'Cynthia', 'Rau', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (5, 'Douglas R.', 'Cobbs', 'Google');
insert into EMPLOYEE (id, first_name, last_name, company) values (6, 'Michael', 'Patel', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (7, 'Suzanne', 'Wong', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (8, 'Ivan C.', 'Jaya', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (9, 'Ida', 'Ketterer', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (10, 'Laina Ochoa', 'Lucero', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (11, 'Wesley M.', 'Montana', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (12, 'Leslie F.', 'McCleary', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (13, 'Sayeed D.', 'Mudra', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (14, 'Pietronella J.', 'Domingo', 'Google');
insert into EMPLOYEE (id, first_name, last_name, company) values (15, 'John S.', 'O''Leary', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (16, 'Gladys D.', 'Smith', 'Google');
insert into EMPLOYEE (id, first_name, last_name, company) values (17, 'Sally O.', 'Thygesen', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (18, 'Rachel', 'Vogt', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (19, 'Julia', 'DeLong', 'Coca-Cola');
insert into EMPLOYEE (id, first_name, last_name, company) values (20, 'Mark T.', 'Rizzoli', 'Google');
insert into EMPLOYEE (id, first_name, last_name, company) values (21, 'Maria J.', 'Angelo', 'Coca-Cola');
